---
title: "Functions"
author: "Wenxin Tian"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(rvest)
```

## Something simple:

```{r}
x_vec = rnorm(30, mean = 5, sd = 3)

(x_vec - mean(x_vec)) / sd(x_vec)
```

Function that computes z-scores:

```{r}
z_score = function(x) {
  z = (x - mean(x)) / sd(x)
  return(z)
}

z_score(x_vec)
```

Checking inputs:

```{r}
z_score = function(x) {
  if(!is.numeric(x)) {
    stop("Input must be numeric")
  } 
  else if (length(x) < 3) {
    stop("Input must have at least 3 numbers")
  }
  z = (x - mean(x)) / sd(x)
  
  mean_x = mean(x)
  sd_x = sd(x)
  
  list(mean = mean_x, sd = sd_x)
}

z_score(x_vec)

z_score = function(x) {
  if(!is.numeric(x)) {
    stop("Input must be numeric")
  } 
  else if (length(x) < 3) {
    stop("Input must have at least 3 numbers")
  }
  z = (x - mean(x)) / sd(x)
  
  mean_x = mean(x)
  sd_x = sd(x)
  
  tibble(mean = mean_x, sd = sd_x)
}

z_score(x_vec)
```

## Multiple Inputs:

```{r}
sim_mean_sd = function(n, mu = 2, sigma = 3) {
  sim_data = tibble(
    x = rnorm(n, mean = mu, sd = sigma)
  )
  
  sim_data |>
    summarize (
      mu_hat = mean(x),
      sigma_hat = sd(x)
    )
}

sim_mean_sd(10)
```


## NSDUH:

```{r}
nsduh_url = "http://samhda.s3-us-gov-west-1.amazonaws.com/s3fs-public/field-uploads/2k15StateFiles/NSDUHsaeShortTermCHG2015.htm"

nsduh_html = read_html(nsduh_url)

data_marj = 
  nsduh_html |> 
  html_table() |> 
  nth(1) |>
  slice(-1) |> 
  select(-contains("P Value")) |>
  pivot_longer(
    -State,
    names_to = "age_year", 
    values_to = "percent") |>
  separate(age_year, into = c("age", "year"), sep = "\\(") |>
  mutate(
    year = str_replace(year, "\\)", ""),
    percent = str_replace(percent, "[a-c]$", ""),
    percent = as.numeric(percent)) |>
  filter(!(State %in% c("Total U.S.", "Northeast", "Midwest", "South", "West")))
```

```{r}
nsduh_table <- function(html, table_num, table_name) {
  
  table = 
    html |> 
    html_table() |> 
    nth(table_num) |>
    slice(-1) |> 
    select(-contains("P Value")) |>
    pivot_longer(
      -State,
      names_to = "age_year", 
      values_to = "percent") |>
    separate(age_year, into = c("age", "year"), sep = "\\(") |>
    mutate(
      year = str_replace(year, "\\)", ""),
      percent = str_replace(percent, "[a-c]$", ""),
      percent = as.numeric(percent),
      name = table_name) |>
    filter(!(State %in% c("Total U.S.", "Northeast", "Midwest", "South", "West")))
}

nsduh_results = 
  bind_rows(
    nsduh_table(nsduh_html, 1, "marj_one_year"),
    nsduh_table(nsduh_html, 4, "cocaine_one_year"),
    nsduh_table(nsduh_html, 5, "heroin_one_year")
  )
```




